### ISSUE TITLE
parametrized dependencies

### ISSUE THREAD

**Issue by alexhsamuel** [apsis-scheduler/apsis#324]
> Could we make conditions dependent on a parameter?

**Comment by alexhsamuel** [comment]
They already are, sort of.  As it stands, the args of the dependent job are template-expanded and support the [Jinja expression syntax](https://jinja.palletsprojects.com/en/3.1.x/templates/#expressions).  For instance,

```yaml
condition:
  type: dependency
  job_id: get borrow
  args:
    region: {{ 'americas' if strat == 'us' else 'emea' if strat == 'eu' else 'asia' }}
```

Currently, the job ID is not similarly expanded, but it could trivially made so.  In that case, we should probably allow a null job ID, which makes the dependency a no-op.  This would make it easy to turn an dependency on and off for a strat.

```yaml
condition:
  type: dependency
  job_id: {{ 'get imbalance' if strat == 'us' else None }}
```

or something like that.  I guess we could add an explicit `enable` option to the dependency, but the above seems more general.

Note that one downside of expanding the job ID like this is that `check-jobs` would necessarily have to be weakened, because it can no longer necessarily check that the dependency job exists and that the correct arguments are supplied.  But the recent dependency-exist feature serves as a run-time check against this, I guess.

Is this what you had in mind?

**Comment by axwest** [comment]
I think something like:
```
condition:
  type: dependency
  enable: {{ 'True' if strat == 'us' else 'False' }}
```

Would do the trick.  CC @lusewell

**Comment by alexhsamuel** [comment]
You prefer this because it's simpler, or because you don't think we should weaken `check-jobs`?  If the former, I'm hesitant; seems to me that expanding `job_id` might prove useful in the future, and that would subsume this pretty neatly.

**Comment by axwest** [comment]
Both to avoid weakening check-jobs and because I think having multiple conditions that are enabled/disabled is more readable than an expanded job_id.

Don’t feel that strongly though.
'

_________________________________________________________

Any and all emails sent to us may be monitored and/or stored by us to ensure compliance with relevant legislation, rules and policies. If we collect and use your personal data you provide us or which we otherwise collect in the course of our business we will use it in accordance with our privacy policy.

This email, its contents, and any attachments transmitted with it are intended only for the addressee(s) and may be confidential and legally privileged. If you are not an addressee or authorized to act on their behalf, do not read, print, re-transmit, or store this email, any information contained in it, or any attachments. We do not waive any confidentiality by misdelivery. If you have received this email in error, please notify the sender immediately and then permanently delete this email from your system.

Any liability for viruses is excluded to the fullest extent permitted by law.

'

**Comment by TedSinger** [comment]
An `enabled` flag would have helped me today. Or allowing FileDependency to take a list or a None.

I had these alternatives:
```yaml
condition: # We want to skip this condition on Saturdays. Depending on a random file instead
  - type: FileDependency
    filename: |
      {% if Date(date).weekday == 5 %}
        /etc/magic
      {% else %}
        /prod/target_file_by_day_{{ Date(date).ymdi }}.gz
      {% endif %}

condition: # We want to skip this condition on Saturdays. Depend on the previous day instead
  - type: FileDependency
    filename: |
      /prod/target_file_by_day_{{ (Date(date) - (Date(date).weekday == 5)).ymdi }}.gz

condition:
  # None. Instead, a custom command determines the filename and handles polling
```
