### ISSUE TITLE
Check missing params in job specs

### ISSUE THREAD

**Issue by chtan-xantium** [apsis-scheduler/apsis#336]
Would it be possible for `check_jobs` to check missing params in job specs? E.g. if we have a command

```
command: run_my_code --custom {{ my_param }}
```
we check that `my_param` is specified in `params`.

This would help catch these spec errors before they are in prod.

**Comment by alexhsamuel** [comment]
This is tricky for two reasons:

1. Not all fields in a program specification are necessarily template-expanded.  It depends on the program type.
2. The template expansion isn't just string substitution; it is a full [Jinja template expansion](https://jinja.palletsprojects.com/en/3.1.x/templates/).  You can evaluate expressions like `{{ int(param) * 2 + 1 }}`.  The only way to check this would be actually to evaluate it, for which we'd need a known-valid set of run args to evaluate with.

**Comment by LudovicoRighi** [comment]
Few examples of recent issues:
### 1
Missing `strat` in `[params]` and in `schedule`'s `args`; notice `strat` here was needed to properly expand `user: trd`.
```
params: [date]

schedule:
  - type: 'daily-interval'
    tz: America/New_York
    calendar: strat/us
    start: '09:00:00'
    stop: '17:00:00'
    interval: 300

program:
  type: asd.lib.ops.apsis.program.ShellProgram
  user: trd
  host: appl40-ny4
  command: python -m ...
```
### 2
Typo; should have been `date` instead of `data`.
```
params: [strat, date]
...
condition:
  - type: dependency
    job_id: ...
    args:
      strat: eu
      date: "{{ get_calendar('eu').before(data) }}"
```
