### ISSUE TITLE
scheduled stop time for Procstar jobs

### ISSUE THREAD

**Issue by alexhsamuel** [apsis-scheduler/apsis#373]
```yaml
# No change from normal runs.
program:
  type: agent
  command: asd-env python -m asd.my.service

# No change from normal runs.
schedule:
  type: daily
  calendar: us
  time: "9:00:00"

# New for services.
stop:
  schedule:
    type: stop_time  # new schedule type; see below
    time: "16:00:00"

  signal: SIGTERM
  # Wait time for process to terminate; then SIGKILL.
  timeout: 1m
```

Stop types:
- signal

Stop schedule types:
- stop_time: next occurrence of daytime after scheduled start time (no calendar)
- duration: time after the actual (not scheduled) start time
- none (eternal)

State model:
new → scheduled → waiting → starting → running → stopping → success / failure

Run completion state:
  failed to start in starting               → error
  any termination in running                → failure
  killed by stop signal in stopping         → success
  exit with status = 0 in stopping          → success
  other termination in stopping             → failure
  if actual start time > stop time: waiting → success  (??)

Questions:
- Conditions? probably
- Actions? probably
- How many services?
- How are they arranged? mixed with other jobs? yes

Antifeatures (not included):
- automatic restarts 
- stop scripts
- conditions / dependencies for stop
- a "service" that isn't a direct child process, e.g. `open_day` + `close_day`
- polling for liveness or responsiveness

Still to do:
- UI sketch

# Todo

- [ ] add a _stopping_ state to state model, UIs
- [ ] use _stopping_ when signaling a running run
- [ ] ...
